local obj = string.trim(matches.obj)
selectCaptureGroup("obj")
setUnderline(true)
setLink([[fetchItem("]] .. obj .. [[")]], obj)
setUnderline(false)
Nf.setInventory(obj)
setTriggerStayOpen("Inventory", 1)
