name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Muddle
        uses: demonnic/build-with-muddler@v1.3

      - name: Upload MPackage
        uses: actions/upload-artifact@v4.4.3
        with:
          name: nukefire.mpkg
          path: build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/nukefire.mpkg
